export default [
    {
        id: 1,
        title: "Lago di Como",
        location: "Italy",
        googleMapsUrl: "https://goo.gl/maps/GdvrYDrydMp3KNhw6",
        startDate: "28 Jun, 2015",
        endDate: "11 Jul, 2015",
        description: "Lake Como, also known as Lario, is a lake of glacial origin in Lombardy, Italy. It has an area of 146 square kilometres (56 sq mi), making it the third-largest lake in Italy, after Lake Garda and Lake Maggiore.",
        imageUrl: "https://images.unsplash.com/photo-1587046377996-01aa69d0e290?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1074&q=80",
        altText: "A view of the village near Lake Como",
        wikiLink: "https://en.wikipedia.org/wiki/Lake_Como"
    },
    {
        id: 2,
        title: "Blarney Castle",
        location: "Ireland",
        googleMapsUrl: "https://goo.gl/maps/Cw2avnpJn5sfBGsV7",
        startDate: "14 Jun, 2016",
        endDate: "30 Jun, 2016",
        description: "Blarney Castle is a medieval stronghold in Blarney, near Cork, Ireland. The Blarney Stone is among the machicolations of the castle.",
        imageUrl: "https://images.unsplash.com/photo-1628581380246-032f10bf1afb?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1229&q=80",
        altText: "An upward view of Blarney Castle",
        wikiLink: "https://en.wikipedia.org/wiki/Blarney_Castle"
    },
    {
        id: 3,
        title: "Llanfair...gogogoch",
        location: "Whales",
        googleMapsUrl: "https://goo.gl/maps/jwqNmXx4qsKhMjeE8",
        startDate: "14 Jun, 2016",
        endDate: "30 Jun, 2016",
        description: "Llanfairpwllgwyngyll, or Llanfairpwllgwyngyllgogerbwlltysiliogogogoch, is a large village and local government community on the island of Anglesey, Wales, on the Menai Strait next to the Britannia Bridge and across the strait from Bangor. The long name was supposedly contrived in 1869 as an early publicity stunt to give the station the longest name of any railway station in Britain.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.JPG/1024px-Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.JPG",
        altText: "The entrance to the James Pringle Weaver shop with the full name of the town printed in front of it in both Welsh and English.",
        wikiLink: "https://en.wikipedia.org/wiki/Llanfairpwllgwyngyll"
    },
    {
        id: 4,
        title: "Loch Ness",
        location: "Scotland",
        googleMapsUrl: "https://goo.gl/maps/yfqYCSad3hCMa6MU7",
        startDate: "14 Jun, 2016",
        endDate: "30 Jun, 2016",
        description: "Loch Ness is a large freshwater loch in the Scottish Highlands extending for approximately 37 kilometres (23 miles) southwest of Inverness. Loch Ness is best known for claimed sightings of the cryptozoological Loch Ness Monster, also known affectionately as 'Nessie'.",
        imageUrl: "https://images.unsplash.com/photo-1561538433-276d3f8e0359?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1169&q=80",
        altText: "A water-side view of Loch Ness with a tall castle towering in the background.",
        wikiLink: "https://en.wikipedia.org/wiki/Loch_Ness"
    },
    {
        id: 5,
        title: "Carlisle Castle",
        location: "England",
        googleMapsUrl: "https://goo.gl/maps/VybmhVynmSjT7jk19",
        startDate: "14 Jun, 2016",
        endDate: "30 Jun, 2016",
        description: "Carlisle Castle is a medieval stone keep castle located in the city of Carlisle near the ruins of Hadrian's Wall. First built during the reign of William II in 1092 and rebuilt in stone under Henry I in 1122, the castle is over 930 years old and has been the scene of many episodes in British history.",
        imageUrl: "https://images.unsplash.com/photo-1656587118264-b422a2b63923?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        altText: "The main turret to Carlisle Castle built out of red-orange bricks",
        wikiLink: "https://en.wikipedia.org/wiki/Carlisle_Castle"
    },
    {
        id: 6,
        title: "Eiffel Tower",
        location: "France",
        googleMapsUrl: "https://goo.gl/maps/sdNZA3GaAep2UPSD9",
        startDate: "19 Jun, 2018",
        endDate: "30 Jun, 2018",
        description: "The Eiffel Tower is a wrought-iron lattice tower on the Champ de Mars in Paris, France. It is named after the engineer Gustave Eiffel, whose company designed and built the tower.",
        imageUrl: "https://images.unsplash.com/photo-1569949380643-6e746ecaa3bd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        altText: "The iron lattice Eiffel tower viewed from a park filled with people on a sunny day partially filled with clouds.",
        wikiLink: "https://en.wikipedia.org/wiki/Eiffel_Tower"
    },
    {
        id: 7,
        title: "Casino de Monte Carlo",
        location: "Monaco",
        googleMapsUrl: "https://goo.gl/maps/H9Q4gipSsnn1mLvK8",
        startDate: "19 Jun, 2018",
        endDate: "30 Jun, 2018",
        description: "The Monte Carlo Casino, officially named Casino de Monte-Carlo, is a gambling and entertainment complex located in Monaco. It includes a casino, the Opéra de Monte-Carlo, and the office of Les Ballets de Monte-Carlo.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Monaco-CasinoMonteCarlo.jpg",
        altText: "The main entrance to the grand casino surrounded by fancy cars and well-dressed people on sunny day.",
        wikiLink: "https://en.wikipedia.org/wiki/Monte_Carlo_Casino"
    },
    {
        id: 8,
        title: "La Sagrada Família",
        location: "Spain",
        googleMapsUrl: "https://goo.gl/maps/sxgak2wJZtE2oVpB9",
        startDate: "19 Jun, 2018",
        endDate: "30 Jun, 2018",
        description: "The Basílica i Temple Expiatori de la Sagrada Família, shortened as the Sagrada Família, is an unfinished church in the Eixample district of Barcelona, Catalonia, Spain. It is the largest unfinished Catholic church in the world.",
        imageUrl: "https://images.unsplash.com/photo-1591612910792-5bedcedb9cc2?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        altText: "An upward view of three of the church towers",
        wikiLink: "https://en.wikipedia.org/wiki/Sagrada_Fam%C3%ADlia"
    },
    {
        id: 9,
        title: "Vientiane",
        location: "Laos",
        googleMapsUrl: "https://goo.gl/maps/m72hWpr9hihhVaTL6",
        startDate: "28 Jan, 2019",
        endDate: "31 Jan, 2019",
        description: "Vientiane is the capital and largest city of Laos. Vientiane is divided administratively into 9 cities with a total area of only approx. 3,920 square kilometres and is located on the banks of the Mekong, close to the Thai border.",
        imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/28/Vientiane_-_Patuxai_-_0003.jpg/1280px-Vientiane_-_Patuxai_-_0003.jpg",
        altText: "The Patuxai in Vientiane; a tall arch with ornately decorated roof surrounded by an outdoor park.",
        wikiLink: "https://en.wikipedia.org/wiki/Vientiane"
    },
    {
        id: 10,
        title: "Taipei 101",
        location: "Taiwan",
        googleMapsUrl: "https://goo.gl/maps/Aeyrd7eLx9J4XQ6S8",
        startDate: "29 Nov, 2019",
        endDate: "3 Dec, 2019",
        description: "Taipei 101, formerly known as the Taipei World Financial Center, is a skyscraper in Taipei, Taiwan. The building was officially classified as the world's tallest from its opening in 2004 until the 2009 completion of the Burj Khalifa in Dubai, UAE.",
        imageUrl: "https://images.unsplash.com/photo-1550760146-f2f4cf8961f1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1171&q=80",
        altText: "Taipei 101 lit up in the color green at night surrounded by the rest of Taipei City's skyscapers.",
        wikiLink: "https://en.wikipedia.org/wiki/Taipei_101"
    },
    {
        id: 11,
        title: "Petronas Twin Towers",
        location: "Malysia",
        googleMapsUrl: "https://goo.gl/maps/A1fK15K4QthEVTMz9",
        startDate: "21 Jan, 2020",
        endDate: "11 Mar, 2020",
        description: "The Petronas Towers, also known as the Petronas Twin Towers or KLCC Twin Towers, are a pair of 88-storey supertall skyscrapers in Kuala Lumpur, Malaysia, standing at 451.9 metres (1,483 feet). From 1998 to 2003, they were officially designated as the tallest buildings in the world until they were surpassed by the 2004 completion of the Taipei 101.",
        imageUrl: "https://images.unsplash.com/photo-1472017053394-b29fded587cd?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        altText: "An upward view of the Petronas Twin Towers and the bridge that connects the two towers.",
        wikiLink: "https://en.wikipedia.org/wiki/Petronas_Towers"
    },
    {
        id: 12,
        title: "Bali",
        location: "Indonesia",
        googleMapsUrl: "https://goo.gl/maps/qWaHMsNB3AqGsE9V7",
        startDate: "26 Mar, 2023",
        endDate: "31 Mar, 2023",
        description: "Bali is a province of Indonesia and the westernmost of the Lesser Sunda Islands. East of Java and west of Lombok, the province includes the island of Bali and a few smaller offshore islands, notably Nusa Penida, Nusa Lembongan, and Nusa Ceningan to the southeast. It is renowned for its highly developed arts, including traditional and modern dance, sculpture, painting, leather, metalworking, and music.",
        imageUrl: "https://images.unsplash.com/photo-1557093793-e196ae071479?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1170&q=80",
        altText: "Stacked rice fields in Ubud, Bali surrounded by lush, green rain forest",
        wikiLink: "https://en.wikipedia.org/wiki/Bali"
    },
    {
        id: 13,
        title: "Krabi",
        location: "Thailand",
        googleMapsUrl: "https://goo.gl/maps/fjrqwJ8cgHAPvA636",
        startDate: "29 Apr, 2023",
        endDate: "1 May, 2023",
        description: "Krabi is the capital of and main town in Krabi Province, on the west coast of southern Thailand, where the Krabi River flows into Phang Nga Bay. Much of the province has been given over to several national parks. Top destinations are Hat Noppharat Thara - Mu Ko Phi Phi National Park, Ao Nang, Railay, and Ko Phi Phi.",
        imageUrl: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1139&q=80",
        altText: "Thai passenger boats lined up along a beach with towering limestone cliffs and blue ocean waters behind them",
        wikiLink: "https://en.wikipedia.org/wiki/Krabi_province"
    }
]